package com.e_book.model

data class UpdateUserProfileResponse(
    val userId: Int,
    val userName: String,
    val firstName: String,
    val lastName: String,
    val email: String,
    val password: String,
    val gender: Int,
    val mobileNo: String,
    val address: String,
    val roleId: Int,
    val aboutUs: String,
    val isActive: Boolean,
    val createdOn: String,
    val createdBy: Int,
  val updated: String,
    val updatedBy: Int,
    val lastLoginDate: String,
    val lastPasswordChange: String,
    val ip: String,
    val deviceId: Any,
    val token: Any,
    val profile: Any,
    val dob: String,
    val tblStickyNotes: List<Any>,
    val tblUserBooks: List<Any>,
)